# Docker Compose for SIH25027 Prototype
# Prototype developed by Team Hackon

version: '3.8'

services:
  # Backend API Service
  backend:
    build: ./backend
    container_name: sih25027-backend
    ports:
      - "5000:5000"
    environment:
      - NODE_ENV=development
      - PORT=5000
      - CORS_ORIGIN=http://localhost:3000
      - SIMULATE_BLOCKCHAIN=true
    volumes:
      - ./backend/data:/app/data
      - ./backend/uploads:/app/uploads
      - ./backend/logs:/app/logs
    networks:
      - sih25027-network
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5000/health"]
      interval: 30s
      timeout: 10s
      retries: 3

  # Frontend Web Application  
  frontend:
    build: ./frontend
    container_name: sih25027-frontend
    ports:
      - "3000:3000"
    environment:
      - REACT_APP_API_BASE_URL=http://localhost:5000/api
      - REACT_APP_MAPBOX_TOKEN=${REACT_APP_MAPBOX_TOKEN}
    depends_on:
      - backend
    networks:
      - sih25027-network
    restart: unless-stopped
    volumes:
      - ./frontend/src:/app/src
      - ./frontend/public:/app/public
    stdin_open: true
    tty: true

  # Nginx Reverse Proxy (Optional)
  nginx:
    image: nginx:alpine
    container_name: sih25027-proxy
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - frontend
      - backend
    networks:
      - sih25027-network
    restart: unless-stopped
    profiles: ["production"]

networks:
  sih25027-network:
    driver: bridge

volumes:
  backend_data:
  backend_uploads:
  backend_logs: